# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

# TODO: add tests

trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm ci
  displayName: 'npm install'

- script: |
    cd frontend && npm run build
  displayName: 'cd frontend && npm run build'

- script: |
    npm run server:bundle
  displayName: 'npm run server:bundle'

- script: |
    rm -rf UI-e2e test frontend/src frontend/node_modules frontend/public
  displayName: 'clean files'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: "e2e-test-output-*.xml"
    searchFolder: '$(System.DefaultWorkingDirectory)/UI-e2e/cytestresults'
    failTaskOnFailedTests: true

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

